function Edges=PolyFace2Edge(PolyFaces)
% ----------------------------------------------------------------------- %
% M-file to convert a FacesCell list to an Edge list
% which can be used for calculation of gravitation
% using the algorithm in 1997 Werner CMDA
% #########################################################################
% Author: Leyuan Wu <leyuanwu@zjut.edu.cn>
%   College of Science, Zhejiang University of Technology, Hangzhou, China
% #########################################################################
% ---- Reference ---- %
% Werner, R.A., Scheeres, D.J. 
% Exterior gravitation of a polyhedron derived and compared with harmonic 
% and mascon gravitation representations of asteroid 4769 Castalia. 
% Celestial Mech Dyn Astr 65, 313-344 (1996). https://doi.org/10.1007/BF00053511
% ----------------------------------------------------------------------- %
% ---- input ---- %
% PolyFaces: Face list: cell array, each face can contain multiple sides
% Note £¡£¡£¡£¡ Each edge can belong to two faces or only one face, 
% which makes it easy to calculate the gravitational effect generated by partial faces
% ---- output ---- %
% Edges: edge list, five columns of data
% **** Start vertex; End vertex; Direction flag; Face number 1; Face number 2 (nan if none exists) **** %
%%%%%%%% Transposed, can concatenate into a long row, the number of elements equal to the number of sides
nEdge=numel(cell2mat(PolyFaces'));
%%%%%%%% Initialize edge list, five columns of data
% **** Start vertex; End vertex; Direction flag; Face number 1; Face number 2 (nan if none exists) **** %
Edges=nan(nEdge,5);
Edges(:,3)=1; % The Direction flag of the edge is initially 1
%%%%%%%% Loop to extract all edges
iEdge=0; % edge index
for iFace=1:1:length(PolyFaces)
    face=PolyFaces{iFace};
    nedge=length(face);
    facee=[face,face(1)];
    Edges(iEdge+1:iEdge+nedge,1)=facee(1:nedge);
    Edges(iEdge+1:iEdge+nedge,2)=facee(2:end);
    Edges(iEdge+1:iEdge+nedge,4)=iFace;
    iEdge=iEdge+nedge;
end
%%%%%%%% If End vertex < Start vertex, switch positions
logSwap=Edges(:,2)<Edges(:,1);
temp=Edges(logSwap,1);
Edges(logSwap,1)=Edges(logSwap,2);
Edges(logSwap,2)=temp;
Edges(logSwap,3)=-1;
%%%%%%%% Sort by vertex number
Edges=sortrows(Edges);
%%%%%%%% Extract the edges belonging to two faces
logCommonEdge=[false;(Edges(2:end,1)==Edges(1:end-1,1)) & (Edges(2:end,2)==Edges(1:end-1,2))];
logDelete=[logCommonEdge(2:end);false];
Edges(logCommonEdge,5)=Edges(logDelete,4);
%%%%%%%% Remove duplicate edges
Edges=Edges(~logDelete,:);

